update

diff --git a/web_server/4-not_found_page_404 b/web_server/4-not_found_page_404
--- a/web_server/4-not_found_page_404
+++ b/web_server/4-not_found_page_404
@@ -1,39 +1,25 @@
 #!/usr/bin/env bash
-# Configures a new ubuntu machine by installing
-# Nginx where it should be listening on port 80
-# Serve a page that would return a Holberton School string
-#
+# Script to configure Nginx with a custom 404 page.
 
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-	 sudo apt-get install nginx -y
+# Exit on errors
+set -e
 
-echo -e "\nSetting up some minor stuff.\n"
+# Update and install Nginx
+sudo apt update
+sudo apt install -y nginx
 
-# starting nginx service
-sudo service nginx start
+# Create the custom 404 page directory and file
+sudo mkdir -p /var/www/html/errors
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/errors/404.html
 
-# allowing nginx on firewall
-sudo ufw allow 'Nginx HTTP'
+# Configure Nginx to use the custom 404 page
+NGINX_CONF="/etc/nginx/sites-available/default"
+sudo sed -i '/server {/a\    error_page 404 /errors/404.html;' $NGINX_CONF
+sudo sed -i '/server {/a\    location = /errors/404.html { root /var/www/html; internal; }' $NGINX_CONF
 
-# Give the user ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+# Reload Nginx to apply changes
+sudo nginx -t
+sudo systemctl reload nginx
 
-# Backup default index
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
-
-# Creating new index
-echo -e "Holberton School" > /var/www/html/index.nginx-debian.html
-
-# Setting up /redirect_me to a youtube video
-sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
-
-# Set up a 404 page
-echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
-sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
-
-# Restarting nginx
-sudo service nginx restart
-
-echo -e "\nCompleted.\n"
+# Ensure proper permissions
+sudo chown -R www-data:www-data /var/www/html/errors
